# Generated by Django 4.0.1 on 2022-01-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
